services:
  - type: web
    name: helpdesk-api
    runtime: node
    rootDir: asses-nest-app
    buildCommand: npm install && npm run build:prod
    startCommand: npm run start:prod
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        sync: false
